- name: Installation du poste de travail
  hosts: all
  connection: local
  become: yes
  roles:
    - role: init
      tags: ['init']


    - role: umanit.gpg
      gpg_key_content: |-
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mI0ESX35nAEEALKDCUDVXvmW9n+T/+3G1DnTpoWh9/1xNaz/RrUH6fQKhHr568F8
        hfnZP/2CGYVYkW9hxP9LVW9IDvzcmnhgIwK+ddeaPZqh3T/FM4OTA7Q78HSvR81m
        Jpf2iMLm/Zvh89ZsmP2sIgZuARiaHo8lxoTSLtmKXsM3FsJVlusyewHfABEBAAG0
        H0xhdW5jaHBhZCBQUEEgZm9yIE9uZMWZZWogU3Vyw72ItgQTAQIAIAUCSX35nAIb
        AwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEE9OoKrlJnpsQjYD/jW1NlIFAlT6
        EvF2xfVbkhERii9MapjaUsSso4XLCEmZdEGX54GQ01svXnrivwnd/kmhKvyxCqiN
        LDY/dOaK8MK//bDI6mqdKmG8XbP2vsdsxhifNC+GH/OwaDPvn1TyYB653kwyruCG
        FjEnCreZTcRUu2oBQyolORDl+BmF4DjL
        =R5tk
        -----END PGP PUBLIC KEY BLOCK-----
      gpg_key_name: php.gpg
      tags: ['gpg-php']

    - role: umanit.full_php
      tags: ['full_php']


    - role: umanit.gpg
      gpg_key_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      gpg_key_name: brave-browser-archive-keyring.gpg
      tags: ['gpg-brave']

    - role: brave
      tags: ['brave']


    - role: umanit.gpg
      gpg_key_url: https://downloads.1password.com/linux/keys/1password.asc
      gpg_key_name: 1password-archive-keyring.gpg
      tags: ['gpg-1password']

    - role: umanit.gpg
      gpg_key_url: https://downloads.1password.com/linux/keys/1password.asc
      gpg_key_path: /usr/share/debsig/keyrings/AC2D62742012EA22/
      gpg_key_name: debsig.gpg
      tags: ['gpg-1password']

    - role: 1password
      tags: ['1password']


    - role: composer
      tags: ['composer']


    - role: umanit.gpg
      gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
      gpg_key_name: docker.gpg
      tags: ['gpg-docker']

    - role: umanit.docker
      tags: ['docker']


    - role: golang
      tags: ['golang']


    - role: symfony-cli
      tags: ['symfony-cli']


    - role: umanit.volta
      tags: ['volta']


    - role: stow
      tags: ['stow']
