---
- name: Ajout du dépôt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
    state: present
    filename: docker

- name: Installation
  apt:
    name: docker-ce,docker-ce-cli,containerd.io,docker-buildx-plugin,docker-compose-plugin
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Création du groupe docker
  group:
    name: docker
    state: present

- name: Ajout au groupe docker
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Ajout à systemd
  systemd:
    name: "{{ item }}.service"
    state: started
    enabled: yes
  loop:
    - docker
    - containerd
