---
- name: Installation des paquets apt
  apt:
    name: "{{ init_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Installation des paquets snap
  snap:
    name: "{{ init_snap_packages }}"
    state: present

- name: Installation des paquets snap (flag classic)
  snap:
    name: "{{ init_snap_classic_packages }}"
    state: present
    classic: true
